## yaml-language-server: $schema=https://armanriazi.github.io/site/mkdocs-material/schema.json

site_name: Arman Riazi
repo_url: https://github.com/armanriazi/armanriazi.github.io
nav:    
    - 'Home':
        - 'Index': 'index.md'
        - 'Walk-through': 'public/public.md'                              
    - 'Blockchain':       
        - 'Blockchain': 'public/blockchain/Blockchain.md'    
    - 'Walk-through': 
        - 'Walk-through': 'public/public.md'          
    - 'Achievements':       
        - 'Achievements': 'achievements.md'                
    - 'Tags':
        - 'Tags': 'tags.md'      
    - 'Links':
        - 'Links': 'links.md'            
    - 'About':
        - 'About': 'about.md'                
theme:
  name: material
  logo: assets/attachments/me.png
  favicon: assets/attachments/favicon.ico
  language: en
  features:    
  - search.suggest
  - search.highlight
  - search.share
  - announce.dismiss
  - content.tooltips
  - content.code.annotate
  - header.autohide
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand  
  - toc.follow

icon:
   admonition:
     note: octicons/tag-16
     abstract: octicons/checklist-16
     info: octicons/info-16
     tip: octicons/squirrel-16
     success: octicons/check-16
     question: octicons/question-16
     warning: octicons/alert-16
     failure: octicons/x-circle-16
     danger: octicons/zap-16
     bug: octicons/bug-16
     example: octicons/beaker-16
     quote: octicons/quote-16
     note: fontawesome/solid/sticky-note
     abstract: fontawesome/solid/book
     info: fontawesome/solid/info-circle
     tip: fontawesome/solid/bullhorn
     success: fontawesome/solid/check
     question: fontawesome/solid/question-circle
     warning: fontawesome/solid/exclamation-triangle
     failure: fontawesome/solid/bomb
     danger: fontawesome/solid/skull
     bug: fontawesome/solid/robot
     example: fontawesome/solid/flask
     quote: fontawesome/solid/quote-left     
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true      
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: armanriazi
      repo: armanriazi.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - tags:
     tags_file: tags.md
  - search
extra_css:
  - assets/css/mkdocs-extra.css
extra_javascript:
  - assets/javascripts/mkdocs-extra.js
  - assets/javascripts/feedback.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  homepage: https://armanriazi.github.io/
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/arman_riazi_science
      name: ArmanRiazi on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/armanriazi
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/armanriazi            
analytics:
  provider: google
  property: G-S8E1J4V9C3
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful  
        note: >- 
          copyright: Copyright &copy; 2023 Arman Riazi
          generator: false
